# Debian (Linux Distribution)  + MySQL 5.7.x
FROM mysql:5.7

# Install appointment - team  database once: - this file for only database only after i have main os and mysql
COPY ./managment.sql /docker-entrypoint-initdb.d


